### ISSUE TITLE
Robinhood API login not returning "account" field

### ISSUE THREAD

**Issue by ialexryan** [aurbano/robinhood-node#1]
Nothing's working, and it seems the reason why is that the Robinhood API is only returning a "token" field for the login request, not a "token" field and an "account" field.

https://github.com/aurbano/robinhood-node/blob/d7cd109a5cb4665b628814096083900f27ccf19a/src/robinhood.js#L90

When I put console.log(body.account) after this line, it's `undefined`.

cc/ @Rohanpai

**Comment by aurbano** [comment]
Thanks for reporting @ialexryan , I have not been able to test the API yet since I don't have an account to access the API yet (I'm based in the UK)

**Comment by dustinmoorenet** [comment]
The account property is not there because body is a zipped string. Setting gzip flag to true gives us the proper JSON response.

**Comment by aurbano** [comment]
Brilliant @dustinmoorenet, thank you very much!
