### ISSUE TITLE
What does `instrument.url` refer to?

### ISSUE THREAD

**Issue by tejasmanohar** [aurbano/robinhood-node#11]
What does `instrument.url` refer to [here](https://github.com/aurbano/robinhood-node#place_buy_orderoptions-callback)? Based on the docs, it seems to be a required field so some clarification could be helpful.

**Comment by aurbano** [comment]
I can't tell for sure at the moment, both for this and for issue #12 since I'm in the UK where I don't have access to Robinhood (they still haven't opened here)

If you manage to find out more information about these fields please let me know or send a pull request, thanks!

**Comment by tejasmanohar** [comment]
Got it. Quite impressive that you got this far w/o Robinhood being open in the UK. I'm in the US and actively use Robinhood so maybe I can help contribute here. I've opened #13— if you could shed some light as to your process here, that'd definitely help, as I haven't done much reverse-engineering of APIs other than just listening to requests in Chrome DevTools' network panel.

**Comment by aurbano** [comment]
Another option without having to intercept all the calls is to use this package to reverse engineer the API further. Now that it can connect and get data, it should be easy to test sending small buy/sell orders and look at the responses.

As soon as they expand to the UK I'll finish covering the rest of the API and probably improve the code by adding classes for instruments, stocks...

**Comment by KamuelaFranco** [comment]
It doesn't seem like they'll be expanding to the UK just yet. Unfortunately, I've had to permanently switch to my UK App Store account, which I just remembered as I was going to help investigate this.

**Comment by tejasmanohar** [comment]
"to my US"? @KamuelaFranco

**Comment by KamuelaFranco** [comment]
Nah, I mean that I have it on the US App Store, but it gets difficult to live in the UK for very long without just switching lol.

**Comment by tejasmanohar** [comment]
Oh, sorry- I misread that completely. My bad.

**Comment by uladkasach** [comment]
An instrument can be considered the entity which a `symbol` is mapped to. I.e., a privately traded company on the stock exchange. Instrument.url = `https://api.robinhood.com/instruments/<instrument-id>/` where `<instrument-id>` maps uniquely to a `symbol`****


**** as far as i know

**Comment by tagroup** [comment]
@uladkasach is correct - "instrument":"https://api.robinhood.com/instruments/39ff611b-84e7-425b-bfb8-6fe2a983fcf3/" is an example of **GE**.  

If you want to build an index, they can be found at [https://api.robinhood.com/instruments/](https://api.robinhood.com/instruments/).  The total equities instruments should be over 12,336.
