### ISSUE TITLE
Possible values for order `type`

### ISSUE THREAD

**Issue by tejasmanohar** [aurbano/robinhood-node#12]
What are the possible values for the `type` option [here](https://github.com/aurbano/robinhood-node#place_buy_orderoptions-callback)?

``` js
{
    bid_price: Number,
    quantity: Number,
    instrument: {
        url: String,
        symbol: String
    },
    // Optional:
    trigger: String, // Defaults to "gfd" (Good For Day)
    time: String,    // Defaults to "immediate"
    // this one below ↓
    type: String     // Defaults to "market"
   // this one ^^^
}
```

**Comment by toymachiner62** [comment]
I would guess that "limit" is an option for `type`

**Comment by aurbano** [comment]
Sounds likely - if anyone could try this and confirm it I'll add it to the docs

**Comment by jspenc72** [comment]
I verified it. "limit" is an option...

**Comment by jspenc72** [comment]
I changed the default to limit in my fork as well as typically I prefer to know what my shares will sell for rather than hope for the best offer...

**Comment by Joshwani** [comment]
So if I wanted to execute a "fill or kill" buy order would i want something like this...

{
        account: account,
        bid_price: bid_price,
        quantity: quantity,
        instrument: {
        url: url,
                symbol: symbol
        }
        trigger: "gtc",
        time: "immediate",
        type: "limit"
},

**Comment by aurbano** [comment]
Yeah the API is much better documented now
