### ISSUE TITLE
No error returned in callback

### ISSUE THREAD

**Issue by nodesocket** [aurbano/robinhood-node#16]
`quote_data` does not return error in callback.

``` javascript
let symbol = 'AAPL';
rh.quote_data(symbol, function(error, response, body) {
    // error does not seem to be set even though an error occurred
    // for example provided invalid login credentials
}
```

**Comment by nodesocket** [comment]
Correction, the case of `quote_data()` does not have an error if you provide invalid login credentials because in-fact you don't need to auth to request this endpoint at all. However it should return `error` when you pass an invalid ticker symbol such as `sfafaffas` yet it does not.

**Comment by aurbano** [comment]
Error reporting will be added in the next major version, currently proposed here #105
