### ISSUE TITLE
Get NASDAQ Composite quote

### ISSUE THREAD

**Issue by nodesocket** [aurbano/robinhood-node#21]
Any idea how to get a NASDAQ Composite quote?

I tried:

```javascript
IXIC
.IXIC (Google) [https://www.google.com/finance?q=INDEXNASDAQ%3A.IXIC]
^IXIC (Yahoo) [http://finance.yahoo.com/q?uhb=uhb2&fr=uh3_finance_vert_gs&type=2button&s=%5EIXIC%2C]
```

Just not sure what Robinhood is using as the symbol.

**Comment by aurbano** [comment]
@nodesocket did you manage to fix this?

**Comment by nodesocket** [comment]
Thanks for following up.

No, not sure what the NASDAQ composite ticker symbol is, or even if Robinhood's quote api exposes it.
