### ISSUE TITLE
Example of how to authenticate?

### ISSUE THREAD

**Issue by fedosejev** [aurbano/robinhood-node#25]
Unfortunately, there is no example of how to authenticate with Robinhood.

I guess this would be the correct way of doing it?

```js
Robinhood({
  username: 'username'
  password: 'password'
}).orders(function () {});
```

Thanks for your efforts!

**Comment by brycelund** [comment]
I had to use the callback function in the initializer to make sure it was all the way authenticated before attempting any other functions.

`var rh = Robinhood({username:'username', password:'password'}, function(){

    rh.positions( function(error, response, body){
        console.log(body);
    });

});`

I haven't tried it the way you posted, but that works for me at least to authenticate and get the current positions. For some reason I have trouble when trying to place an order.

**Comment by busse** [comment]
I've used this project as an example implementation as I work on building my own script: https://github.com/markalfred/robinhood-to-csv

Using the `prompt` package, it shows:

```javascript
function login () {
  return new Promise((resolve, reject) => {
    prompt.message = prompt.delimeter = ''
    prompt.start()
    prompt.get({
      properties: {
        username: { default: process.env.ROBINHOOD_USERNAME, required: true },
        password: { default: process.env.ROBINHOOD_PASSWORD, required: true, hidden: true }
      }
    }, (err, res) => {
      if (err) {
        reject(err)
      } else {
        R = robinhood({ username: res.username, password: res.password }, resolve)
      }
    })
  })
}
```

I haven't previously used Promises in node, so that project has taught me a few things.

**Comment by aurbano** [comment]
@busse using promises would make this a lot cleaner, so I've been thinking of adding them to this for a while. The only "downside" is that native support was fairly recent so I stayed away from it for now.

Also the docs need to be updated with authenticated examples, I'll try to spend some time on this soon. thanks!

**Comment by andreipopovici** [comment]
@aurbano I was just about to add Promises in my fork of robinhood-node. Did you, by any chance, get around to doing this? It would be a waste to duplicate the effort.

Otherwise, I'd be glad to try it and start a PR.

**Comment by aurbano** [comment]
@andreipopovici I haven't had the time to get started on it, but if you go for it I'll be happy to merge it into the proyect

**Comment by caviles** [comment]
The API seems to work great for me on unauthenticated calls. I see the login fn setting the token. However, when I call the API I get an error that says the token is invalid. Can anyone offer any guidance on this? I've tried sniffing the traffic using a proxy but the app detects I am doing so and blocks me. I've tried the example from brycelund and could not successfully get back my positions even though login got a token. Any help would be greatly appreciated. Thanks in advance!

**Comment by brycelund** [comment]
Can you post your code? What I had posted should still work

**Comment by caviles** [comment]
Hey brycelund, 

I must have somehow munged something up. I copied a second time and tried again, it's working great. Thanks for the lightning fast reply.

**Comment by jspenc72** [comment]
Do something like this

```typescript
var credentials = require("credentials.js")()
var Robinhood = require('robinhood')
    colors  = require('colors');

var Robinhood = require('robinhood')(credentials, function(){
	console.log("Connected!".green);
	Robinhood.create_watch_list('Technology', function(err, response, body){
		if(err){
			console.error(err);
		}else{
			console.log("created watchlist");
			console.log(body);
		}
	})
});
```
where credentials.js is a file containing something of the form:
```typescript

module.exports = function () {
	'use strict';
	var credentials = {
		username: '', 
		password: ''
	};
	return credentials
}
```
