### ISSUE TITLE
oco order type?

### ISSUE THREAD

**Issue by busse** [aurbano/robinhood-node#26]
The README makes mention of an oco order type. Has that been tested and if so is there an example of how to call that? Is it two consecutive orders or different parameters sent in one?

**Comment by sanko** [comment]
Right above that reads...
> [Disclaimer: This is an unofficial API based on reverse engineering, and the following option values have not been confirmed]

Not sure where @aurbano got `oco` but the only supported order types I've found are `market` and `limit`. Someone should make a PR to fix that and...

- switch trigger and time documentation (their listed possible values are swapped)
- add immediate-or-cancel (`ioc`), fill-or-kill (`fok`) and on-the-open (`opg`) to time
- add `on_close` and `stop` (which will then require `stop_price` param) to trigger
- etc. etc. etc.
