### ISSUE TITLE
README.md is innaccurate with regard to order triggers & time

### ISSUE THREAD

**Issue by busse** [aurbano/robinhood-node#28]
For awareness, these sections of the README.md are inaccurate:

https://github.com/aurbano/robinhood-node#trigger
https://github.com/aurbano/robinhood-node#time
https://github.com/aurbano/robinhood-node#trigger-1
https://github.com/aurbano/robinhood-node#time-1

What is described as triggers are actually time in force, and vice versa. There is a trigger of `stop` as well, and possibly `on_close` (on market close, need to test). There may also be other viable time values (`fok`, `ioc`...).

Most of this I am getting from: https://github.com/sanko/Finance-Robinhood/blob/master/lib/Finance/Robinhood/Order.pm

I am working on a README.md update to correct this which I will submit a PR for once I test all the options from the perl library above.

**Comment by sanko** [comment]
API documentation for orders may be found here: https://github.com/sanko/Finance-Robinhood/blob/master/API.md#place-an-order

**Comment by aurbano** [comment]
Thanks for your PR @busse , just merged it. I'll revisit the readme today and ideally spend some time improving the code as well.

@sanko I hadn't seen that project but it seems like a really good resource as well, specially their documentation, thanks!

**Comment by sanko** [comment]
@busse & @aurbano, I'm organizing the documentation of the API and putting it in its own repo this weekend. Makes things easier for people who want to keep track of any changes I make there but don't care to see all the updates I make to my Perl client. Linking to different parts should be a lot easier too.

Check it out over here: https://github.com/sanko/Robinhood/

**Comment by aurbano** [comment]
@sanko added a link to your docs, really clean! As soon as I have some time I'll use them to update the readme here and improve the client.
