### ISSUE TITLE
Code Orders

### ISSUE THREAD

**Issue by caviles** [aurbano/robinhood-node#34]
I noticed cancel orders was missing. To implement it you will need this URL https://api.robinhood.com/orders/<orderid>/cancel/. The orderid comes in the response of the order. Thanks for for posting this API.

**Comment by jspenc72** [comment]
Ill see if i can take care of it.

**Comment by jspenc72** [comment]
Thanks for this!

**Comment by jspenc72** [comment]
@caviles do you know if the endpoint expects a POST or DELETE request?
