### ISSUE TITLE
cancel_order not working

### ISSUE THREAD

**Issue by viabox** [aurbano/robinhood-node#43]
cancel_order not working when i try it on a queued order.

**Comment by aurbano** [comment]
Thanks for reporting it, do you get any error message that may help debug this?

**Comment by swimclan** [comment]
I submitted a PR to fix this.

**Comment by aurbano** [comment]
Merged, released in [v0.8.0](https://github.com/aurbano/robinhood-node/releases/tag/v0.8.0)
