### ISSUE TITLE
Authentication Models

### ISSUE THREAD

**Issue by swimclan** [aurbano/robinhood-node#48]
Does the RH API support OAuth or SAML SSO authentication methods?  Or is sending a clear-text username and password the only way to authenticate an account?  I couldnt find anything in their documentation but thought I would ask anyway.

**Comment by aurbano** [comment]
@swimclan I started writing an answer a while back but then decided to do some more research before.

As far as I know, their API uses user/pass. I doubt they have SAML at this stage, although maybe you can reach out to their support and ask. If they do it wouldn't be hard at all to figure out the API endpoints for it and implement it on our end...
