### ISSUE TITLE
'Invalid Token' response

### ISSUE THREAD

**Issue by swimclan** [aurbano/robinhood-node#49]
I am getting intermittent `{ detail: 'Invalid token' }` responses from the API when making use of the `.url` method to get an instrument object from an instrument URL.  Here is an example instrument URL that I am using that will fail with the above message intermittently:

`https://api.robinhood.com/instruments/80cd401e-7b50-4372-8a1f-a8562971962a/`

Could this be related to my login token with the API?  I am making several consecutive calls to the API with my credentials and wonder if the expire is causing this to fail?  Does the token need to be refreshed?  The intermittent nature of this issue makes me think that time has something to do with it...

**Comment by swimclan** [comment]
I figured this out.  I was instantiating a new instance of the library with each API call.  Now I am caching the instance of RH node and it is running with no issues.  Its also quite fast...

**Comment by AHStudyBank** [comment]
Hey man, going through this now. How did you end up caching the instance?

**Comment by swimclan** [comment]
@AHStudyBank at a high level, I used app.locals in ExpressJS.  I created a "session" class that stored the instance of RH-Node that could be accessed through middleware on every route of my application.  That way I was sharing a singleton instance of the module that was authenticated with Robinhood once and only once.

**Comment by prmichaelsen** [comment]
I see, so I should only instantiate an instance once. Hm. Unless I expire a token when I'm done, perhaps.
