### ISSUE TITLE
[Error: options.uri is a required argument]

### ISSUE THREAD

**Issue by nodesocket** [aurbano/robinhood-node#5]
Calling `quote_data` seeing an error:

````
[Error: options.uri is a required argument]
````

**Comment by aurbano** [comment]
Thank you for reporting it @nodesocket, I don't have an API token since the service is US only for now and I'm based on the UK, so I developed the API a bit "blindly".

I'll fix this, and also try to get a token again so I can finally test it. Cheers

**Comment by nodesocket** [comment]
Just you just provide your `username` and `password` into the constructor? Not sure where the token is coming from. Thanks.

**Comment by dustinmoorenet** [comment]
This was fixed in https://github.com/aurbano/robinhood-node/commit/fd44c9c0df6b8635ebaf5461a04526729f33a662 it just hasn't been release to npm.

**Comment by aurbano** [comment]
published v0.1.0 that should fix this
