### ISSUE TITLE
Rate limits?

### ISSUE THREAD

**Issue by austinyearlykim** [aurbano/robinhood-node#55]
AWESOME library @aurbano 

Specifically talking about the quote_data method.  Is there any sort of rate limiting so my IP doesn't get banned into oblivion?  Is 60 requests a minute per SYMBOL reasonable?

I tried to do some due diligence, but I wasn't lucky in finding any documentation on any sort of rate limit.

Please and thank you!

Best,
Austin

**Comment by aurbano** [comment]
As far as I know, they don't support using their API directly - so they probably won't mention rate limiting anywhere.

But I would guess they have rate limiting in place so use with care!

**Comment by napindc** [comment]
@austinyearlykim what was the most amount of calls you could do to their service without getting banned?
