### ISSUE TITLE
Cancel an order by order id

### ISSUE THREAD

**Issue by uladkasach** [aurbano/robinhood-node#68]
It should be possible to cancel an order by specifying the order id, rather than needing the full order object. 

The uri request `https://api.robinhood.com/orders/<order_id>/cancel` is easily buildable.

**Comment by uladkasach** [comment]
The pull request is backwards compatible: the same operations result if an order object is passed (as the method originally expected).

**Comment by uladkasach** [comment]
I've confirmed through live testing that this new functionality works as expected and confirmed that  the previous functionality works as expected (backwards compatible.)

**Comment by aurbano** [comment]
Sorry for the delay merging this! Added in 1.4.0
