### ISSUE TITLE
Typings for TypeScript

### ISSUE THREAD

**Issue by evanshortiss** [aurbano/robinhood-node#81]
Would you be open to merging a PR to add a `robinhood.d.ts` file that enables typescript support? This could also benefit plain JS users since it would provide improved typeahead etc.

**Comment by aurbano** [comment]
Absolutely, it would make a lot of sense to write in TS, please feel free to send a PR

**Comment by evanshortiss** [comment]
@aurbano awesome, just made a PR and build seems to be passing 👍 Thanks
