### ISSUE TITLE
Update LICENSE file to MIT

### ISSUE THREAD

**Issue by evanshortiss** [aurbano/robinhood-node#82]
The `package.json` says this project is MIT, but the repo contains a LICENSE file stating it is the `GNU AFFERO GENERAL PUBLIC LICENSE`.

Which is correct? Either the `package.json` needs to state `SEE LICENSE IN LICENSE`, or the LICENSE file should be MIT, right?

**Comment by aurbano** [comment]
Good catch! I think it started as AGPL but then changed to MIT, I'll change the license file now
