### ISSUE TITLE
`.d.ts` should not include `enum` declarations

### ISSUE THREAD

**Issue by prmichaelsen** [aurbano/robinhood-node#92]
I'm happy to fix this in a PR. But basically, to my knowledge, one should not define actual values in a Typescript `d.ts` file. They are not importable as values, only as types. Instead, one would declare
`type Time: 'day' | 'immediate'` and specify `time` as type of `Time` where it is used.

Please correct me if there is something I am missing. Otherwise, I will create the changes and a open a PR for this issue.

**Comment by aurbano** [comment]
Makes sense @prmichaelsen, feel free to send a PR!

**Comment by prmichaelsen** [comment]
added PR #93
