### ISSUE TITLE
Robinhood asked me to stop using their API

### ISSUE THREAD

**Issue by chiefsmurph** [aurbano/robinhood-node#97]
maybe it's time for a change to the headers?  also async await support would be great.

**Comment by alogwe** [comment]
wow, that's kind of surprising.. what did they say?

**Comment by chiefsmurph** [comment]
@alogwe 

```We noticed that you may be trading through an API (Application Programming Interface). We’re excited to offer you commission-free trading, but we can’t allow you to transact with an API.

In the meantime, we’ll need you to take the following steps to keep using Robinhood:

Upload a photo of your government-issued I.D. into your Robinhood app when you’re prompted.

Respond to this email with an explanation of your trading and confirmation that you will no longer transact with an API.

If we haven’t heard from you in 3 days, we may have to prevent you from placing buy orders until we receive your response. 

...```

**Comment by alogwe** [comment]
interesting.. thanks for sharing that. i agree it'd be nice to be able to change headers (also the async/await is always nice to have haha)

**Comment by thehaitiancoder** [comment]
Can anyone say something more on this? I have been thinking of building a bot for my daily trades, should I get started anyway? What's the chance that Robinhood blocks the access to this API (that one day it simply doesn't answer) or worse close my account?

**Comment by chiefsmurph** [comment]
@thehaitiancoder here are my thoughts... you might be able to get away with using the Robinhood API for data if you don't put it under too much pressure.  I think they really just don't want people executing orders using the API but maybe they'll look the other way just for data?  I don't know.  

I have been looking into alternatives and these are some other options:

1. Alpaca
2. Interactive Brokers
3. TD Ameritrade

all offer data options if you sign up for an account

**Comment by JoshuaJWilborn** [comment]
I don't understand why they care about the use of the API...As long as you have money and are trading with them. It's not like they are making add revenue.  Very strange!  

Perhaps what we should do is require user-agent to be set manually on initialization, so everyone has a unique one.

As for async await, I know I'm new here but my opinion is that async await bring there own problems.  I would support a refactor to promises over callbacks though.  In fact, if the community thinks that would be a good improvement I don't mind doing the work.

**Comment by tpwatson** [comment]
Maybe they just dont want their servers inundated with requests when they are already not taking trade execution commissions. If we can start executing automatically then it doesnt let the interest build up from your account when the money is just sitting there.

**Comment by aurbano** [comment]
Since this is not an issue of the library directly I'll close it, but discussion is obviously more than welcome as it will be useful for others that find this via search engines.
